### ISSUE TITLE
Fix Dynamic Tests to use reflection to invoke methods to test since we now use explicit interface implementations

### ISSUE THREAD

**Issue by jamesbascle** [Jagged/OneOf#15]
Related to this comment https://github.com/Jagged/OneOf/issues/13#issuecomment-279950490

Would you like to do the change on your side then I'll pull into my branch, or do you want me to fix it and do a PR or what?

I like the idea of the test, it's just a pretty challenging one to implement w/o dynamism.

**Comment by Jagged** [comment]
I can certainly do that.

**Comment by jamesbascle** [comment]
Think it's reader for this if you would like.

**Comment by Jagged** [comment]
I've reverted the tests so they don't need reflection, all pass now.
