### ISSUE TITLE
When clauses?

### ISSUE THREAD

**Issue by jamesbascle** [Jagged/OneOf#6]
I was suggested this by some folks who gave the library a look.  Similar to the When clauses as seen in C#7, F#, and other functional languages, we should enable a .When method during matching to additionally filter on conditions relevant to the specific type.

I *think* this can be accomplished without a huge rewrite of the OneOfMatcher flow to use a builder, but I'm not 100% on that.

Thoughts?

**Comment by Jagged** [comment]
Yep, we could do with something like that.  It pains me that this was pulled from C# 7.  We've got the updated switch statement which could effectively remove half of our code, but not the match side of things.

I like how you emphasised "think", I totally get how grand ideas and reality are often two different things! =)

So, hmm, syntax...

.MatchWhen<Rectangle>(r => r.Length == r.Width, r => "It's a square")
.Match<Rectangle>(r => "Nope, it's a rectangle")   // matches Rectangles if the earlier one didn't

This shouldn't reduce the arity, leaving Rectangle available for another match.

Thoughts?

**Comment by Jagged** [comment]
I've added MatchWhen, could you please review and see how it feels?  I'll start on SwitchWhen next.

**Comment by Jagged** [comment]
And SwitchWhen added too.

**Comment by jamesbascle** [comment]
I think that works.  Would be Nice to be able to structure it as When(...).Match(...), but I think it leaves open a good bit of ambiguity.

I'll try to get a release of this change into NuGet/DiscU this weekend.

**Comment by Jagged** [comment]
As you say, we could try to make the syntax closer to what was originally proposed for C# 7's match, being something like:

```c#
oo.Match<string>()   // need to know TResult, but maybe we can infer it from the following Then's?
.When<Rectangle>(r => r.Length==r.Width).Then(r=> "square")
.When<Rectangle>().Then(r=>"rectangle")
.Else("?????");
```

I dunno, the MatchWhen is easier to just get on with things.  The other sounds like fun to implement, but a whole lot of typing to use it...

**Comment by jamesbascle** [comment]
Yeah I agree.  I may give it a go sometime in the next couple of weeks, but I think your implementation is totally fine.
