### ISSUE TITLE
Trimming equality comparisons

### ISSUE THREAD

**Issue by Jagged** [Jagged/OneOf#7]
@jamesbascle , I've been thinking of stripping down the equality comparisons to encourage use of Match and MatchWhen.  Thoughts?

**Comment by Jagged** [comment]
Done.  Feedback?

**Comment by jamesbascle** [comment]
Not sure how I feel about this TBH.  Essentially your change makes it so that the only way to see if two OneOf's are equal is to do a Match, then a Match on the other inside, and then do that for each type case?

**Comment by Jagged** [comment]
Does this affect any of your production code?  It seems odd to be comparing OneOf's, but Equals will do it if needed.  I left that and GetHashCode for use in dictionaries etc.

If there's a use-case that makes good use of operator == or != then I'll happily put it back.  I was attempting to strip OneOf down to it's core functionality, but I may have been overzealous?

**Comment by jamesbascle** [comment]
Hm.  If anything I would say that the operators would compare values, and
the Equals would just call reference equals.  And no, I don't think it
affects any of my code. Though I'm not at a computer until tomorrow.

**Comment by jamesbascle** [comment]
Went over all your changes. Mostly looks fine to me.

I came up with the following non-compiling code, due to not having symmetric OneOf overloads.

```using NUnit.Framework;

namespace OneOf.Tests
{
    public class EqTest
    {
        [Test]
        public void a()
        {
            var s = "testing123";
            var b = true;
            var s2 = c(s);
            var b2 = c(b);

            Assert.IsTrue(s2 == s);
            Assert.IsTrue(s == s2);
            Assert.IsTrue(b2 == b);
            Assert.IsTrue(b == b2);
        }

        public OneOf<string, bool, int> c(OneOf<string, bool, int> o)
        {
            return o;
        }
    }
}
```

This is a regression.  My last release of DiscU on Nov6 (0.0.16) passes correctly.

Attempting to fix it by adding 

```
        public static bool operator ==(TOneOf v2, OneOfBase<TOneOf> v1) => Equals(v2, v1);
        public static bool operator !=(TOneOf v2, OneOfBase<TOneOf> v1) => !Equals(v2, v1);
```

to OneOfBase causes a number of [ambiguous operator compiler errors](https://msdn.microsoft.com/en-us/library/w23z7ctw.aspx) in the EqualityOperatorTests [here](https://github.com/Jagged/OneOf/blob/master/OneOf.Tests/EqualityOperatorTests.cs#L22) and [here](https://github.com/Jagged/OneOf/blob/master/OneOf.Tests/EqualityOperatorTests.cs#L34).

**Comment by Jagged** [comment]
Thanks for your feedback James!  I've moved the equality code back up to the OneOf to solve those issues, but...

I'd still discourage use of equality as that defeats the whole point of Match and Switch, but it's there ... for now.  I'm tempted to deprecate it so any use of == or !=  will generate compiler warnings, and remove them in a few months.

To be really draconian towards this goal, I've removed IOneOf to remove the ability to read the OneOf's Value and OrigType.   As a bonus that sped things up a little.

But as I said at the beginning, if there's a good use-case for keeping things as they were, I'm open to it.  Otherwise Match and Switch will be the only way to work with OneOfs in the future.

(puts on boxing gloves to prepare for hearty debate)

**Comment by jamesbascle** [comment]
Oh, but because of the explicit casting, the values get automatically type cast to a OneOf on use of equality comparer. Hmmm.

**Comment by Jagged** [comment]
Yep, the implicit casts take care of those cases, so comparing myOneOf == 10 and also myDict[10] works.

We do need some implicit conversion tests, among others.  I've got a script somewhere that sets up code coverage reporting, so we can easily see that we've got everything tested.  I'll dig that out, it's with my other project I mentioned that supports multi-target nuget packages.

**Comment by Jagged** [comment]
As things stand, are you happy with the current equality functionality?  I'll close this if that's the case and open another for the code coverage.

**Comment by Jagged** [comment]
Cheers, keep 'em coming!
