### ISSUE TITLE
Removing OneOfBase

### ISSUE THREAD

**Issue by Jagged** [Jagged/OneOf#8]
@jamesbascle , I'm thinking of getting rid of OneOfBase classes.  It never really made sense (to me) to use it as a base type for the likes of Yes/No etc.  I'd remove the types that come pre-cooked that hang off them.

Thoughts?

**Comment by Jagged** [comment]
Idle hands... done.  Also changed OneOf to class, which has slowed constructors slightly and sped up Match a similar amount.  Feedback?

**Comment by jamesbascle** [comment]
I have no problem with it really, though I might have gone the other way and removed the struct and keep the base/classes.  But yeah i guess there's no reason for that to be baked in - though it's no longer a drop-in replacement for the original, which is alright I suppose.

**Comment by Jagged** [comment]
I forgot to mention, I'd made OneOf a class so it can be used as a base class if needed.

We'd dropped backwards compatibility ages ago when we dropped the original mega-Match and mega-Switch functions for the builder-style instead.  About the only thing true to the original is the name now.

Do the changes affect any of your production code?

**Comment by jamesbascle** [comment]
Oh yeah, I see. And I don't think it affects anything I'm using. I'm just
using the implicit conversions and the match functions.

**Comment by Jagged** [comment]
The pre-made subclasses were very basic and didn't offer much above what a boolean or enum already gives us.  They're good for demonstration purposes at best, but Harry's original examples within the readme.md are much better.

Hmm, I'm very opinionated of late! Please feel free to cut me down to size if you see a hole in my logic!

**Comment by jamesbascle** [comment]
Nah I agree pretty much.  They don't offer much besides an example of what you can do with it.

**Comment by Jagged** [comment]
Sweet, I'll close this for now then.  Lemme know if anything else related comes to mind.
